name: Michael Mckeever
description: Freelance Digital Designer & Front-end Developer, Belfast
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: pretty

author: Michael Mckeever

logo: /images/dist/android-chrome-384x384.png

# Social
social:
  name: Michael Mckeever
  links:
    - https://twitter.com/mmckvr
    - https://github.com/mckeever02
  twitter:
    username: mmckvr
    url: https://twitter.com/
  github:
    username: mckeever02
    url: https://github.com/
  instagram:
    username: mckeever02
    url: https://instagram.com/
  dribbble:
    username: Mick_Mckeever
    url: https://dribbble.com/
  email: mckeever02@gmail.com

webmaster_verifications:
  google: IMC-lwHL5ZqPd7MdL2mVE5N_7fILL5b7bkwiq-q4yss

#directores
imageurl: /images/dist/
videourl: /videos/

# Global classes
link_classes: link underline-hover blue hover-blue active-black
code_classes: bg-washed-blue pv1
post_heading_classes: f3 lh-title
paragraph_classes: f6 f5-ns

# Gems
gems:
  - jekyll-archives
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

# Settings for archives
jekyll-archives:
  enabled:
    - categories
  layouts:
    category: 'category-archive'
  permalinks:
    category: '/category/:name/'

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Custom configs
daily_rate: £300
hourly_rate: £40

# Navigation
navigation:
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Hire me
    url: /hire-me/
