# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael McKeever | Product Designer
description: > # this means to ignore newlines until "baseurl:"
  Michael McKeever is a digital product designer from Belfast
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

exclude: [
  'node_modules'
]

permalink: pretty

plugins:
  - jekyll-turbolinks

collections:
  case-studies:
    output: true
    permalink: /:collection/:name

sass:
  style: compressed

# Build settings
markdown: kramdown

navigation:
  - text: 'About'
    url: '/about'
  - text: 'Case Studies'
    url: /#case-studies
  - text: 'Contact'
    url: '/#contact'